name: Deploy na AWS

on:
  push:
    tags:
      - 'v*' # Spustí sa iba pri pushe tagu (napr. v1.0.2)

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Stiahnutie kódu
        uses: actions/checkout@v4

      - name: Nastavenie Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22 # Aktualizované na najnovšiu stabilnú verziu 22

      - name: Inštalácia Serverless Frameworku (Bezplatná V3)
        run: npm install -g serverless@3

      - name: Konfigurácia AWS údajov
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWSACCESSKEYID }}
          aws-secret-access-key: ${{ secrets.AWSSECRETACCESSKEY }}
          aws-region: eu-central-1

      - name: Deploy aplikácie
        run: serverless deploy
        working-directory: ./seminar # Upravené podľa tvojej štruktúry z logu